# Generated by Django 3.1.13 on 2021-11-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211130_2329'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoices',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='orederItems',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
