# Generated by Django 3.1.13 on 2021-12-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_shippingadress_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='adress',
            new_name='address',
        ),
    ]
