# Generated by Django 3.1.13 on 2021-12-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20211210_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='codeOrder',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
